### ISSUE TITLE
Defining r_f and \alpha for CoP trajectory

### ISSUE THREAD

**Issue by BvanHofslot** [jrl-umi3218/CaptureProblemSolver#3]
This is rather a question than an issue. Currently I am only using this c++ code (not the python implementations).
How can I compute the predicted CoM + CoP trajectory from the solution \phi? I thought I would need \alpha and r_f from Eq. 66 from "Capturability-based Analysis, Optimization and Control of 3D Bipedal Walking".
Are \alpha and r_f from Eq. 66 somewhere defined or is this part of the optimization? The paper mentions e.g. r_f in the center of the polygon and \alpha can be chosen or optimized externally. Is maybe \alpha from the technical report Section 3.1 the same \alpha of the CoP trajectory, or where can I find this in the code? 

Thank you in advance,
Boris

**Comment by stephane-caron** [comment]
> How can I compute the predicted CoM + CoP trajectory from the solution \phi?

To get time trajectories `CoM(t)` and `CoP(t)`, you can integrate the piecewise-constant segments lambda_i of your solution \phi (computed by Eq. 51) using Eq. 71 from the paper.

You can find Python code that does this in the `CaptureSolution` class at https://github.com/stephane-caron/capture-walking/blob/master/capture_walking/capture_solution.py. (I will add a C++ code for this for convenience.)

> Are \alpha and r_f from Eq. 66 somewhere defined or is this part of the optimization?

The target CoP r_f is indeed given by the user (center of the target contact area, or projection of the ankle frame to minimize ankle torques).

The external optimization is done over \alpha: intervals of alpha's that yield feasible problems are pre-computed by Algorithm 2 to speed up computations, then values of alpha are picked in these intervals (the simplest way is to do a grid search) and CPS is called for each of these. See e.g. the Python code at https://github.com/stephane-caron/capture-walking/blob/master/capture_walking/one_step.py#L164

Hoping this helps!

**Comment by stephane-caron** [comment]
The C++ implementation is now released in the [capture_walking_controller](https://github.com/stephane-caron/capture_walking_controller). Here are some pointers for:

- [Computation of the initial and target CoP's r_i and r_f](https://github.com/stephane-caron/capture_walking_controller/blob/b3df3dadb2699ba7fa38db34b0c95a887ac41636/src/CaptureSolution.cpp#L43)
- [Optimization of internal cost over alpha](https://github.com/stephane-caron/capture_walking_controller/blob/b3df3dadb2699ba7fa38db34b0c95a887ac41636/src/CaptureProblem.cpp#L140)
- [External optimization over alpha to realize a desired contact-switch time](https://github.com/stephane-caron/capture_walking_controller/blob/b3df3dadb2699ba7fa38db34b0c95a887ac41636/src/CaptureProblem.cpp#L210)
- [Computation of CoM(t) by forward integration of capture solution](https://github.com/stephane-caron/capture_walking_controller/blob/b3df3dadb2699ba7fa38db34b0c95a887ac41636/src/CaptureSolution.cpp#L213)

Feel free to re-open this issue if you have further questions on this.
